package com.jsite.manager.role;

public enum DataScope {
	DATA_SCOPE_ALL, DATA_SCOPE_COMPANY_AND_CHILD, DATA_SCOPE_COMPANY, DATA_SCOPE_OFFICE_AND_CHILD, DATA_SCOPE_OFFICE, DATA_SCOPE_SELF, DATA_SCOPE_CUSTOM
}
